image: registry.rudin.io/ci/deploy-runner

variables:
 GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test

luacheck:
 stage: lint
 script:
  - cd mods/eco_buildings && luacheck .
  - cd ../eco_mapgen && luacheck .
  - cd ../eco_placement && luacheck .
  - cd ../eco_stairsplus && luacheck .
  - cd ../eco_activity && luacheck .
  - cd ../builtin_disable && luacheck .
