local MP = minetest.get_modpath("eco_buildings")

eco_buildings = {}

dofile(MP .. "/util/streetname.lua")
dofile(MP .. "/categories.lua")
dofile(MP .. "/randomizer.lua")
dofile(MP .. "/conditions.lua")
dofile(MP .. "/street.lua")
dofile(MP .. "/dirt_street.lua")
dofile(MP .. "/house.lua")
dofile(MP .. "/house_2.lua")
dofile(MP .. "/shop.lua")
dofile(MP .. "/park.lua")
dofile(MP .. "/block.lua")
dofile(MP .. "/strut.lua")
dofile(MP .. "/stone_quarry.lua")
dofile(MP .. "/forestry.lua")
dofile(MP .. "/plot.lua")
dofile(MP .. "/transmission_line.lua")