name: integration-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: textbook/git-checkout-submodule-action@2.0.0

    - name: integration-test
      run: ./test/integration-test.sh
